### ISSUE TITLE
Dodgy wavelength calibration for a Th-Ar arc

### ISSUE THREAD

**Issue by svw26** [mattyowl/RSSMOSPipeline#19]
Hiya Matt,

Long time no speak, hope you and the family are well!

I've created an arc model for an RSS longslit set-up that uses Th-Ar as the lamp, with grating angle = 12.5 deg.
[PG0900_Th Ar_2x4.txt](https://github.com/mattyowl/RSSMOSPipeline/files/7539287/PG0900_Th.Ar_2x4.txt)
[The .pickle file won't attach, but let me know if you need it.]

Each of the wavelengthCalibModelFit_* plots and arcTransformTest_* plots look fine, but the skyCheck_* plots show that something is amiss. For example:
![skyCheck_SLIT1](https://user-images.githubusercontent.com/16702076/141798939-4f3f37bc-5b46-4c69-a0a6-4e0d58f1fe77.png)

And then looking in skyWavelengthCalibCheck.csv the numbers are:
#extension	medianOffsetAngstroms	numLines
SLIT1	-13.383	2
SLIT2	-13.280	2
SLIT3	-13.669	2
SLIT4	-13.462	2
all slits median	-13.422	4
all slits RMS	13.449	4

So if there are not enough sky-lines across the observed wavelength range, is it OK to ignore the results of skyWavelengthCalibCheck.csv and proceed? Or is there something else I should try?

Best wishes,
Sarah x

**Comment by mattyowl** [comment]
Hi Sarah,

The sky line wavelength is just a check, so you _can_ ignore it if you're confident it's not right. If you're just measuring redshifts, it might not be a problem, depending on what accuracy you need. If you're doing something more sophisticated, then maybe it is a cause for concern.

Looking at your plot, perhaps here the wavelength solution becomes wacky when it gets to the red end of this spectrum, but is otherwise ok? Perhaps you don't have so many lines in your arc spectrum at the red end, and so the model fit is free to wander off in that region?

If your actual object spectrum is high enough S/N, you should be able to see by overplotting spectral templates whether e.g. the actual emission/absorption lines line up with the template, or not (that may be tricky if you're looking at e.g. a broad line AGN). Maybe it's ok at the blue end but not at the red end, and if you don't have lines that you care about at the red end, you could ignore it.

Cheers
Matt

**Comment by svw26** [comment]
Hey Matt,

Many thanks -- yeah, the emission lines I'm targeting are at the blue end, and we've picked them up well! (E.g. a distinctive Lyman-alpha/NV profile.) I've used a quasar template to deduce the correct spacing, and found that the following transformation (using the 5577-A skyline as an 'anchor') allows me to get things lining up nicely:

`transformed_wavelength = -0.941172 * (5577.0 - wavelength) + 5577.0` 

With the original wavelength scaling/calibration I was getting z = 2.10, and now (following the transformation above) I get z = 2.15.

Thanks,
Sarah x
